# Generated by Django 5.0.14 on 2026-06-19 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tenantmembership",
            name="tenant",
        ),
        migrations.RemoveField(
            model_name="tenantmembership",
            name="user",
        ),
        migrations.DeleteModel(
            name="Tenant",
        ),
        migrations.DeleteModel(
            name="TenantMembership",
        ),
    ]
