# Generated by Django 5.0.14 on 2026-06-19 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IntegrationConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(blank=True, max_length=255)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("trello", "Trello"),
                            ("jira", "Jira"),
                            ("clickup", "ClickUp"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "project_id",
                    models.CharField(
                        help_text="External project/board identifier at the provider.",
                        max_length=128,
                    ),
                ),
                ("credentials", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["provider", "name"],
                "indexes": [
                    models.Index(
                        fields=["provider", "project_id"],
                        name="tip_integra_provide_203335_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CanonicalTaskRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_provider", models.CharField(db_index=True, max_length=32)),
                ("source_id", models.CharField(max_length=128)),
                ("title", models.CharField(max_length=500)),
                ("status", models.CharField(blank=True, max_length=255)),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                ("project_id", models.CharField(db_index=True, max_length=128)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="tip_integrations.integrationconnection",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["source_provider", "project_id"],
                        name="tip_integra_source__385a69_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="canonicaltaskrecord",
            constraint=models.UniqueConstraint(
                fields=("connection", "source_provider", "source_id"),
                name="unique_canonical_task_per_connection",
            ),
        ),
    ]
