# Generated by Django 5.0.14 on 2026-06-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tip_integrations", "0001_initial_integration_engine"),
    ]

    operations = [
        migrations.AddField(
            model_name="integrationconnection",
            name="workspace_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="External workspace/organization identifier (Trello organization).",
                max_length=128,
            ),
        ),
        migrations.AddIndex(
            model_name="integrationconnection",
            index=models.Index(
                fields=["provider", "workspace_id"],
                name="tip_integra_provide_61d89b_idx",
            ),
        ),
    ]
