# Generated by Django 5.0.14 on 2026-06-19 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tip_integrations", "0002_add_workspace_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="integrationconnection",
            name="project_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="External project/board identifier at the provider.",
                max_length=128,
            ),
        ),
    ]
