# Generated by Django 5.0.14 on 2026-06-19 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tip_integrations", "0003_allow_blank_project_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="IngestionQueueEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("event_type", models.CharField(db_index=True, max_length=64)),
                ("provider", models.CharField(db_index=True, max_length=32)),
                ("connection_id", models.CharField(db_index=True, max_length=64)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("processed", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["provider", "processed", "created_at"],
                        name="tip_integra_provide_6512ea_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="IntegrationIngestionState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("provider", models.CharField(db_index=True, max_length=32)),
                ("cursor", models.JSONField(blank=True, default=dict)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingestion_states",
                        to="tip_integrations.integrationconnection",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["provider", "connection"],
                        name="tip_integra_provide_addb54_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="integrationingestionstate",
            constraint=models.UniqueConstraint(
                fields=("connection", "provider"),
                name="unique_ingestion_state_per_connection_provider",
            ),
        ),
    ]
