# Generated by Django 5.0.14 on 2026-06-19 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tip_integrations", "0005_integration_state"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="integrationstate",
            new_name="tip_integra_provide_6204fc_idx",
            old_name="tip_integra_provide_addb54_idx",
        ),
        migrations.RenameIndex(
            model_name="integrationstate",
            new_name="tip_integra_provide_8fdcc4_idx",
            old_name="tip_integra_provide_8a1f2c_idx",
        ),
        migrations.AlterField(
            model_name="integrationstate",
            name="connection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="integration_states",
                to="tip_integrations.integrationconnection",
            ),
        ),
    ]
