# Generated by Django 5.0.14 on 2026-06-26 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_initial"),
        (
            "tip_integrations",
            "0006_rename_tip_integra_provide_addb54_idx_tip_integra_provide_6204fc_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="integrationconnection",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="integration_connections",
                to="core.tenant",
            ),
        ),
    ]
