# Generated by Django 5.0.14 on 2026-06-26 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tip_settings", "0001_workspace_config"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspaceconfig",
            name="openai_model",
            field=models.CharField(default="gpt-4.1-mini", max_length=64),
        ),
    ]
