# Generated by Django 5.0.14 on 2026-06-20 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("trello", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CardEnrichment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("objective", models.TextField(blank=True)),
                ("area", models.CharField(blank=True, max_length=255)),
                ("department", models.CharField(blank=True, max_length=255)),
                ("project", models.CharField(blank=True, max_length=255)),
                ("client", models.CharField(blank=True, max_length=255)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("ALTA", "Alta"),
                            ("MÉDIA", "Média"),
                            ("BAIXA", "Baixa"),
                        ],
                        default="MÉDIA",
                        max_length=16,
                    ),
                ),
                ("urgency", models.CharField(default="MÉDIA", max_length=16)),
                ("complexity", models.CharField(default="MÉDIA", max_length=16)),
                ("impact", models.CharField(default="MÉDIA", max_length=16)),
                ("criticality", models.CharField(default="MÉDIA", max_length=16)),
                ("business_value", models.CharField(default="MÉDIA", max_length=16)),
                ("confidence", models.FloatField(default=0.0)),
                ("signals_json", models.JSONField(blank=True, default=list)),
                ("context_json", models.JSONField(blank=True, default=dict)),
                (
                    "card",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrichment",
                        to="trello.card",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="KnowledgeBaseEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("lesson_learned", "Lição aprendida"),
                            ("best_practice", "Boa prática"),
                            ("recurring_problem", "Problema recorrente"),
                            ("operational_pattern", "Padrão operacional"),
                            ("root_cause", "Causa raiz"),
                            ("recommendation", "Recomendação"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("content", models.TextField()),
                ("confidence", models.FloatField(default=0.0)),
                ("metadata_json", models.JSONField(blank=True, default=dict)),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knowledge_entries",
                        to="trello.board",
                    ),
                ),
                (
                    "card",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="knowledge_entries",
                        to="trello.card",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Knowledge base entries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OperationalScoreSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("score", models.PositiveSmallIntegerField()),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("Verde", "Verde"),
                            ("Amarelo", "Amarelo"),
                            ("Laranja", "Laranja"),
                            ("Vermelho", "Vermelho"),
                        ],
                        max_length=16,
                    ),
                ),
                ("delivery", models.PositiveSmallIntegerField(default=0)),
                ("deadline", models.PositiveSmallIntegerField(default=0)),
                ("quality", models.PositiveSmallIntegerField(default=0)),
                ("communication", models.PositiveSmallIntegerField(default=0)),
                ("execution", models.PositiveSmallIntegerField(default=0)),
                ("risks", models.PositiveSmallIntegerField(default=0)),
                ("productivity", models.PositiveSmallIntegerField(default=0)),
                ("details_json", models.JSONField(blank=True, default=dict)),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operational_scores",
                        to="trello.board",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TimelineEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("CARD_CREATED", "Card Created"),
                            ("CARD_MOVED", "Card Moved"),
                            ("CARD_ASSIGNED", "Card Assigned"),
                            ("CARD_UNASSIGNED", "Card Unassigned"),
                            ("LABEL_ADDED", "Label Added"),
                            ("LABEL_REMOVED", "Label Removed"),
                            ("COMMENT_ADDED", "Comment Added"),
                            ("CHECKLIST_STARTED", "Checklist Started"),
                            ("CHECKLIST_COMPLETED", "Checklist Completed"),
                            ("CHECKLIST_ITEM_COMPLETED", "Checklist Item Completed"),
                            ("DUE_DATE_CHANGED", "Due Date Changed"),
                            ("CARD_COMPLETED", "Card Completed"),
                            ("CARD_REOPENED", "Card Reopened"),
                            ("ATTACHMENT_ADDED", "Attachment Added"),
                            ("BLOCKER_REGISTERED", "Blocker Registered"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        db_index=True,
                        max_length=64,
                    ),
                ),
                ("event_timestamp", models.DateTimeField(db_index=True)),
                ("actor", models.CharField(blank=True, max_length=255)),
                ("payload_json", models.JSONField(blank=True, default=dict)),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeline_events",
                        to="trello.board",
                    ),
                ),
                (
                    "card",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeline_events",
                        to="trello.card",
                    ),
                ),
                (
                    "source_action",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="timeline_events",
                        to="trello.action",
                    ),
                ),
            ],
            options={
                "ordering": ["-event_timestamp"],
                "indexes": [
                    models.Index(
                        fields=["board", "-event_timestamp"],
                        name="tip_intelli_board_i_542c80_idx",
                    ),
                    models.Index(
                        fields=["card", "-event_timestamp"],
                        name="tip_intelli_card_id_006641_idx",
                    ),
                    models.Index(
                        fields=["board", "event_type"],
                        name="tip_intelli_board_i_8ef85b_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="timelineevent",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_action__isnull", False)),
                fields=("source_action", "event_type"),
                name="unique_timeline_event_per_action_type",
            ),
        ),
    ]
