# Generated by Django 5.0.14 on 2026-06-20 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tip_intelligence", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("generated_by", models.CharField(default="anonymous", max_length=255)),
                ("board_id", models.CharField(db_index=True, max_length=64)),
                ("report_type", models.CharField(db_index=True, max_length=32)),
                ("export_format", models.CharField(default="json", max_length=16)),
                ("filters_json", models.JSONField(default=dict)),
                ("matched_cards", models.PositiveIntegerField(default=0)),
                ("processing_ms", models.PositiveIntegerField(default=0)),
                ("cache_hit", models.BooleanField(default=False)),
                ("result_summary", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["board_id", "-created_at"],
                        name="tip_intelli_board_i_9c90b1_idx",
                    ),
                    models.Index(
                        fields=["generated_by", "-created_at"],
                        name="tip_intelli_generat_8a639f_idx",
                    ),
                ],
            },
        ),
    ]
