# Generated by Django 5.0.14 on 2026-06-17 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Board",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "trello_id",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("url", models.URLField(blank=True, max_length=500)),
                ("closed", models.BooleanField(default=False)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "trello_id",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("username", models.CharField(blank=True, max_length=255)),
                ("full_name", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "ordering": ["full_name", "username"],
            },
        ),
        migrations.CreateModel(
            name="Action",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "trello_id",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("action_type", models.CharField(db_index=True, max_length=64)),
                ("raw_json", models.JSONField(default=dict)),
                ("occurred_at", models.DateTimeField(db_index=True)),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="trello.board",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actions",
                        to="trello.member",
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at"],
            },
        ),
        migrations.CreateModel(
            name="BoardList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "trello_id",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("name", models.CharField(max_length=255)),
                ("position", models.FloatField(default=0)),
                ("closed", models.BooleanField(default=False)),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lists",
                        to="trello.board",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "name"],
            },
        ),
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "trello_id",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True)),
                ("status", models.CharField(blank=True, max_length=255)),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("is_closed", models.BooleanField(default=False)),
                ("is_removed", models.BooleanField(default=False)),
                ("labels", models.JSONField(blank=True, default=list)),
                ("url", models.URLField(blank=True, max_length=500)),
                ("position", models.FloatField(blank=True, null=True)),
                ("last_activity_at", models.DateTimeField(blank=True, null=True)),
                ("raw_json", models.JSONField(blank=True, default=dict)),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cards",
                        to="trello.board",
                    ),
                ),
                (
                    "board_list",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cards",
                        to="trello.boardlist",
                    ),
                ),
                (
                    "assignees",
                    models.ManyToManyField(
                        blank=True, related_name="cards", to="trello.member"
                    ),
                ),
            ],
            options={
                "ordering": ["position", "title"],
            },
        ),
        migrations.CreateModel(
            name="Snapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("snapshot_date", models.DateField(db_index=True)),
                ("state_json", models.JSONField(default=dict)),
                ("card_count", models.PositiveIntegerField(default=0)),
                ("list_count", models.PositiveIntegerField(default=0)),
                ("member_count", models.PositiveIntegerField(default=0)),
                ("action_count", models.PositiveIntegerField(default=0)),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="trello.board",
                    ),
                ),
            ],
            options={
                "ordering": ["-snapshot_date"],
            },
        ),
        migrations.CreateModel(
            name="CardStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("status", models.CharField(max_length=255)),
                ("board_list_trello_id", models.CharField(blank=True, max_length=64)),
                ("board_list_name", models.CharField(blank=True, max_length=255)),
                ("effective_at", models.DateTimeField(db_index=True)),
                (
                    "source",
                    models.CharField(
                        choices=[("sync", "Sync"), ("action", "Action")],
                        default="sync",
                        max_length=16,
                    ),
                ),
                (
                    "board_list",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="card_status_history",
                        to="trello.boardlist",
                    ),
                ),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="trello.card",
                    ),
                ),
                (
                    "source_action",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="card_status_changes",
                        to="trello.action",
                    ),
                ),
            ],
            options={
                "ordering": ["-effective_at"],
                "indexes": [
                    models.Index(
                        fields=["card", "-effective_at"],
                        name="trello_card_card_id_c7dfb6_idx",
                    ),
                    models.Index(
                        fields=["card", "status"], name="trello_card_card_id_5e7c24_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="EntityHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("board", "Board"),
                            ("list", "List"),
                            ("card", "Card"),
                            ("member", "Member"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("entity_trello_id", models.CharField(db_index=True, max_length=64)),
                ("state_json", models.JSONField(default=dict)),
                ("effective_at", models.DateTimeField(db_index=True)),
                (
                    "source",
                    models.CharField(
                        choices=[("sync", "Sync"), ("action", "Action")],
                        default="sync",
                        max_length=16,
                    ),
                ),
                (
                    "board",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entity_histories",
                        to="trello.board",
                    ),
                ),
                (
                    "source_action",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="entity_histories",
                        to="trello.action",
                    ),
                ),
            ],
            options={
                "ordering": ["-effective_at"],
                "indexes": [
                    models.Index(
                        fields=["entity_type", "entity_trello_id", "-effective_at"],
                        name="trello_enti_entity__f02c5c_idx",
                    ),
                    models.Index(
                        fields=["board", "-effective_at"],
                        name="trello_enti_board_i_0cf52f_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="card",
            index=models.Index(
                fields=["board", "status"], name="trello_card_board_i_943f31_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="card",
            index=models.Index(
                fields=["board", "is_closed"], name="trello_card_board_i_2e3947_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="action",
            index=models.Index(
                fields=["board", "action_type"], name="trello_acti_board_i_baee5f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="action",
            index=models.Index(
                fields=["board", "-occurred_at"], name="trello_acti_board_i_039a1d_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="snapshot",
            constraint=models.UniqueConstraint(
                fields=("board", "snapshot_date"), name="unique_board_snapshot_date"
            ),
        ),
    ]
