# Generated by Django 5.0.14 on 2026-06-26 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_initial"),
        ("trello", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trello_boards",
                to="core.tenant",
            ),
        ),
    ]
