from __future__ import annotations

from datetime import timedelta
from pathlib import Path
from typing import Any

from django.db.models import Avg, Count, Sum
from django.utils import timezone

from apps.intelligence.models import (
    ActionExecutionLog,
    ActionImpactFollowUp,
    DecisionFeedbackRecord,
    DecisionRecord,
    PilotConfig,
)
from apps.intelligence.services.business_value.pipeline import build_executive_value_dashboard
from apps.intelligence.services.pilot.evaluation import compute_pilot_metrics


def generate_executive_daily_report(
    *,
    board_id: str,
    pilot: PilotConfig | None = None,
    output_path: str = "",
) -> str:
    """Generate daily executive report — suggested vs executed, value, risks, efficiency."""
    today = timezone.now().date()
    day_start = timezone.now().replace(hour=0, minute=0, second=0, microsecond=0)

    metrics = compute_pilot_metrics(board_id=board_id, since=day_start)
    value_dash = build_executive_value_dashboard(board_id=board_id, days=1)

    pending = DecisionRecord.objects.filter(
        board_id=board_id,
        status__in=["OPEN", "PENDING_APPROVAL"],
    ).count()
    executed_today = ActionExecutionLog.objects.filter(
        created_at__gte=day_start,
        status="EXECUTED",
    ).count()
    blocked_today = ActionExecutionLog.objects.filter(
        created_at__gte=day_start,
        status="BLOCKED",
    ).count()

    critical_ignored = DecisionFeedbackRecord.objects.filter(
        board_id=board_id,
        disposition=DecisionFeedbackRecord.Disposition.IGNORED,
        created_at__gte=day_start,
        original_action_json__contains={"execution_mode": "SEMI_AUTOMATIC"},
    ).count()

    followups_due = ActionImpactFollowUp.objects.filter(
        board_id=board_id,
        status=ActionImpactFollowUp.Status.SCHEDULED,
        scheduled_at__lte=timezone.now(),
    ).count()

    team = pilot.team_name if pilot else "—"
    board_name = pilot.board_name if pilot else board_id

    lines = [
        f"# Executive Daily Report — {today.isoformat()}",
        "",
        f"**Board:** {board_name} (`{board_id}`)  ",
        f"**Team:** {team}  ",
        f"**Mode:** Human-in-the-loop (no auto-execution)",
        "",
        "## Decision Summary",
        "",
        f"| Metric | Value |",
        f"|--------|-------|",
        f"| Suggestions generated (pilot period) | {metrics['suggestions_total']} |",
        f"| Accepted | {metrics['accepted_count']} ({metrics['acceptance_rate_pct']}%) |",
        f"| Ignored | {metrics['ignored_count']} |",
        f"| Modified | {metrics['modified_count']} |",
        f"| Executed today | {executed_today} |",
        f"| Pending queue | {pending} |",
        f"| Blocked today | {blocked_today} |",
        "",
        "## Value — Estimated vs Realized",
        "",
        f"| Metric | BRL |",
        f"|--------|-----|",
        f"| Losses avoided (24h window) | R$ {value_dash['summary']['losses_avoided_brl']:,.2f} |",
        f"| Value created | R$ {value_dash['summary']['value_created_brl']:,.2f} |",
        f"| Avg ROI | {value_dash['summary']['avg_roi_pct']}% |",
        f"| Avg prediction confidence | {value_dash['summary']['avg_confidence']} |",
        "",
        "## Top Risks Detected",
        "",
    ]

    for item in metrics.get("top_risks", [])[:5]:
        lines.append(f"- **{item.get('priority', 'MEDIUM')}** — {item.get('insight', '')[:120]}")

    if not metrics.get("top_risks"):
        lines.append("- No critical open decisions in queue.")

    lines.extend([
        "",
        "## Critical Ignored Suggestions",
        "",
        f"Count today: **{critical_ignored}**",
        "",
        "## System Efficiency",
        "",
        f"| KPI | Value |",
        f"|-----|-------|",
        f"| Acceptance rate target | ≥60% |",
        f"| Current acceptance rate | {metrics['acceptance_rate_pct']}% |",
        f"| Impact follow-ups pending | {followups_due} |",
        f"| Pilot success score | {metrics['success_score']}/100 |",
        "",
        "## Narratives",
        "",
    ])

    for narrative in value_dash.get("narratives", []):
        lines.append(f"- {narrative}")

    lines.extend([
        "",
        "---",
        f"*Generated by POCL at {timezone.now().isoformat()}*",
    ])

    content = "\n".join(lines)
    path = output_path or str(Path("reports") / "executive_daily_report.md")
    out = Path(path)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(content, encoding="utf-8")
    return str(out.resolve())
